package pojos;
// Generated Aug 5, 2020 4:10:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Class generated by hbm2java
 */
public class Class  implements java.io.Serializable {


     private Long id;
     private Grade grade;
     private String code;
     private String name;
     private Boolean isdeleted;
     private Date createddate;
     private String createdby;
     private Date modifieddate;
     private String modifiedby;
     private Set scores = new HashSet(0);
     private Set observations = new HashSet(0);
     private Set formteacherassignments = new HashSet(0);
     private Set teacherassignments = new HashSet(0);
     private Set conducts = new HashSet(0);
     private Set studentofclasses = new HashSet(0);

    public Class() {
    }

	
    public Class(Date createddate, Date modifieddate) {
        this.createddate = createddate;
        this.modifieddate = modifieddate;
    }
    public Class(Grade grade, String code, String name, Boolean isdeleted, Date createddate, String createdby, Date modifieddate, String modifiedby, Set scores, Set observations, Set formteacherassignments, Set teacherassignments, Set conducts, Set studentofclasses) {
       this.grade = grade;
       this.code = code;
       this.name = name;
       this.isdeleted = isdeleted;
       this.createddate = createddate;
       this.createdby = createdby;
       this.modifieddate = modifieddate;
       this.modifiedby = modifiedby;
       this.scores = scores;
       this.observations = observations;
       this.formteacherassignments = formteacherassignments;
       this.teacherassignments = teacherassignments;
       this.conducts = conducts;
       this.studentofclasses = studentofclasses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Grade getGrade() {
        return this.grade;
    }
    
    public void setGrade(Grade grade) {
        this.grade = grade;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
    public String getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Set getScores() {
        return this.scores;
    }
    
    public void setScores(Set scores) {
        this.scores = scores;
    }
    public Set getObservations() {
        return this.observations;
    }
    
    public void setObservations(Set observations) {
        this.observations = observations;
    }
    public Set getFormteacherassignments() {
        return this.formteacherassignments;
    }
    
    public void setFormteacherassignments(Set formteacherassignments) {
        this.formteacherassignments = formteacherassignments;
    }
    public Set getTeacherassignments() {
        return this.teacherassignments;
    }
    
    public void setTeacherassignments(Set teacherassignments) {
        this.teacherassignments = teacherassignments;
    }
    public Set getConducts() {
        return this.conducts;
    }
    
    public void setConducts(Set conducts) {
        this.conducts = conducts;
    }
    public Set getStudentofclasses() {
        return this.studentofclasses;
    }
    
    public void setStudentofclasses(Set studentofclasses) {
        this.studentofclasses = studentofclasses;
    }




}


