package pojos;
// Generated Aug 5, 2020 4:10:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Formteacherassignment generated by hbm2java
 */
public class Formteacherassignment  implements java.io.Serializable {


     private Long id;
     private Class class;
     private Schoolyear schoolyear;
     private Teacher teacher;
     private Integer capacity;
     private Boolean isdeleted;
     private Date createddate;
     private String createdby;
     private Date modifieddate;
     private String modifiedby;

    public Formteacherassignment() {
    }

	
    public Formteacherassignment(Date createddate, Date modifieddate) {
        this.createddate = createddate;
        this.modifieddate = modifieddate;
    }
    public Formteacherassignment(Class class, Schoolyear schoolyear, Teacher teacher, Integer capacity, Boolean isdeleted, Date createddate, String createdby, Date modifieddate, String modifiedby) {
       this.class = class;
       this.schoolyear = schoolyear;
       this.teacher = teacher;
       this.capacity = capacity;
       this.isdeleted = isdeleted;
       this.createddate = createddate;
       this.createdby = createdby;
       this.modifieddate = modifieddate;
       this.modifiedby = modifiedby;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Class getClass() {
        return this.class;
    }
    
    public void setClass(Class class) {
        this.class = class;
    }
    public Schoolyear getSchoolyear() {
        return this.schoolyear;
    }
    
    public void setSchoolyear(Schoolyear schoolyear) {
        this.schoolyear = schoolyear;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
    public String getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }




}


