package pojos;
// Generated Aug 5, 2020 10:41:27 PM by Hibernate Tools 4.3.1

import qlhsc3.Generic;
import java.util.Date;

/**
 * FormTeacherAssignment generated by hbm2java
 */
public class FormTeacherAssignment extends Generic implements java.io.Serializable {

    private SchoolClass schoolClass;
    private SchoolYear schoolYear;
    private Teacher teacher;
    private Integer capacity;

    public FormTeacherAssignment() {
    }

    public FormTeacherAssignment(SchoolClass schoolClass, SchoolYear schoolYear, Teacher teacher, Integer capacity, Boolean isDeleted, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
        this.schoolClass = schoolClass;
        this.schoolYear = schoolYear;
        this.teacher = teacher;
        this.capacity = capacity;
        this.isDeleted = isDeleted;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.modifiedDate = modifiedDate;
        this.modifiedBy = modifiedBy;
    }

    public SchoolClass getSchoolClass() {
        return this.schoolClass;
    }

    public void setSchoolClass(SchoolClass schoolClass) {
        this.schoolClass = schoolClass;
    }

    public SchoolYear getSchoolYear() {
        return this.schoolYear;
    }

    public void setSchoolYear(SchoolYear schoolYear) {
        this.schoolYear = schoolYear;
    }

    public Teacher getTeacher() {
        return this.teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    public Integer getCapacity() {
        return this.capacity;
    }

    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

}
