package pojos;
// Generated Aug 5, 2020 10:41:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import qlhsc3.Officer;

/**
 * HRStaff generated by hbm2java
 */
public class HRStaff extends Officer implements java.io.Serializable {


    public HRStaff() {
    }

    public HRStaff(Account account, String code, String name, String phone, String avatarpath, String gender, Date birth, String address, Integer salary, Boolean isDeleted, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
        this.account = account;
        this.code = code;
        this.name = name;
        this.phone = phone;
        this.avatarpath = avatarpath;
        this.gender = gender;
        this.birth = birth;
        this.address = address;
        this.salary = salary;
        this.isDeleted = isDeleted;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.modifiedDate = modifiedDate;
        this.modifiedBy = modifiedBy;
    }



}
