package pojos;
// Generated Aug 5, 2020 10:41:27 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Performance generated by hbm2java
 */
public class Performance  implements java.io.Serializable {


     private Long id;
     private String code;
     private String name;
     private Float lowerbound;
     private Float upperbound;
     private Float control;
     private Boolean isdeleted;
     private Date createddate;
     private String createdby;
     private Date modifieddate;
     private String modifiedby;

    public Performance() {
    }

	
    public Performance(Date createddate, Date modifieddate) {
        this.createddate = createddate;
        this.modifieddate = modifieddate;
    }
    public Performance(String code, String name, Float lowerbound, Float upperbound, Float control, Boolean isdeleted, Date createddate, String createdby, Date modifieddate, String modifiedby) {
       this.code = code;
       this.name = name;
       this.lowerbound = lowerbound;
       this.upperbound = upperbound;
       this.control = control;
       this.isdeleted = isdeleted;
       this.createddate = createddate;
       this.createdby = createdby;
       this.modifieddate = modifieddate;
       this.modifiedby = modifiedby;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getLowerbound() {
        return this.lowerbound;
    }
    
    public void setLowerbound(Float lowerbound) {
        this.lowerbound = lowerbound;
    }
    public Float getUpperbound() {
        return this.upperbound;
    }
    
    public void setUpperbound(Float upperbound) {
        this.upperbound = upperbound;
    }
    public Float getControl() {
        return this.control;
    }
    
    public void setControl(Float control) {
        this.control = control;
    }
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
    public String getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }




}


