package pojos;
// Generated Aug 5, 2020 10:41:27 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Relatives generated by hbm2java
 */
public class Relatives  implements java.io.Serializable {


     private Long id;
     private Relationship relationship;
     private Student student;
     private String name;
     private String phone;
     private String email;
     private String job;
     private Date birth;
     private String address;
     private Boolean isdeleted;
     private Date createddate;
     private String createdby;
     private Date modifieddate;
     private String modifiedby;

    public Relatives() {
    }

	
    public Relatives(Date createddate, Date modifieddate) {
        this.createddate = createddate;
        this.modifieddate = modifieddate;
    }
    public Relatives(Relationship relationship, Student student, String name, String phone, String email, String job, Date birth, String address, Boolean isdeleted, Date createddate, String createdby, Date modifieddate, String modifiedby) {
       this.relationship = relationship;
       this.student = student;
       this.name = name;
       this.phone = phone;
       this.email = email;
       this.job = job;
       this.birth = birth;
       this.address = address;
       this.isdeleted = isdeleted;
       this.createddate = createddate;
       this.createdby = createdby;
       this.modifieddate = modifieddate;
       this.modifiedby = modifiedby;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Relationship getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(Relationship relationship) {
        this.relationship = relationship;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public Date getBirth() {
        return this.birth;
    }
    
    public void setBirth(Date birth) {
        this.birth = birth;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
    public String getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }




}


