package pojos;
// Generated Aug 5, 2020 4:10:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Schoolyear generated by hbm2java
 */
public class Schoolyear  implements java.io.Serializable {


     private Long id;
     private String code;
     private Integer lowerbound;
     private Integer upperbound;
     private String theme;
     private Boolean isdeleted;
     private Date createddate;
     private String createdby;
     private Date modifieddate;
     private String modifiedby;
     private Set teacherassignments = new HashSet(0);
     private Set observations = new HashSet(0);
     private Set studentofclasses = new HashSet(0);
     private Set conducts = new HashSet(0);
     private Set formteacherassignments = new HashSet(0);
     private Set scores = new HashSet(0);

    public Schoolyear() {
    }

	
    public Schoolyear(Date createddate, Date modifieddate) {
        this.createddate = createddate;
        this.modifieddate = modifieddate;
    }
    public Schoolyear(String code, Integer lowerbound, Integer upperbound, String theme, Boolean isdeleted, Date createddate, String createdby, Date modifieddate, String modifiedby, Set teacherassignments, Set observations, Set studentofclasses, Set conducts, Set formteacherassignments, Set scores) {
       this.code = code;
       this.lowerbound = lowerbound;
       this.upperbound = upperbound;
       this.theme = theme;
       this.isdeleted = isdeleted;
       this.createddate = createddate;
       this.createdby = createdby;
       this.modifieddate = modifieddate;
       this.modifiedby = modifiedby;
       this.teacherassignments = teacherassignments;
       this.observations = observations;
       this.studentofclasses = studentofclasses;
       this.conducts = conducts;
       this.formteacherassignments = formteacherassignments;
       this.scores = scores;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Integer getLowerbound() {
        return this.lowerbound;
    }
    
    public void setLowerbound(Integer lowerbound) {
        this.lowerbound = lowerbound;
    }
    public Integer getUpperbound() {
        return this.upperbound;
    }
    
    public void setUpperbound(Integer upperbound) {
        this.upperbound = upperbound;
    }
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
    public String getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Set getTeacherassignments() {
        return this.teacherassignments;
    }
    
    public void setTeacherassignments(Set teacherassignments) {
        this.teacherassignments = teacherassignments;
    }
    public Set getObservations() {
        return this.observations;
    }
    
    public void setObservations(Set observations) {
        this.observations = observations;
    }
    public Set getStudentofclasses() {
        return this.studentofclasses;
    }
    
    public void setStudentofclasses(Set studentofclasses) {
        this.studentofclasses = studentofclasses;
    }
    public Set getConducts() {
        return this.conducts;
    }
    
    public void setConducts(Set conducts) {
        this.conducts = conducts;
    }
    public Set getFormteacherassignments() {
        return this.formteacherassignments;
    }
    
    public void setFormteacherassignments(Set formteacherassignments) {
        this.formteacherassignments = formteacherassignments;
    }
    public Set getScores() {
        return this.scores;
    }
    
    public void setScores(Set scores) {
        this.scores = scores;
    }




}


