package pojos;
// Generated Aug 5, 2020 4:10:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Score generated by hbm2java
 */
public class Score  implements java.io.Serializable {


     private Long id;
     private Class class;
     private Schoolyear schoolyear;
     private Scoretype scoretype;
     private Semester semester;
     private Student student;
     private Subject subject;
     private Float value;
     private Integer ordinalnumber;
     private Boolean isdeleted;
     private Date createddate;
     private String createdby;
     private Date modifieddate;
     private String modifiedby;

    public Score() {
    }

	
    public Score(Date createddate, Date modifieddate) {
        this.createddate = createddate;
        this.modifieddate = modifieddate;
    }
    public Score(Class class, Schoolyear schoolyear, Scoretype scoretype, Semester semester, Student student, Subject subject, Float value, Integer ordinalnumber, Boolean isdeleted, Date createddate, String createdby, Date modifieddate, String modifiedby) {
       this.class = class;
       this.schoolyear = schoolyear;
       this.scoretype = scoretype;
       this.semester = semester;
       this.student = student;
       this.subject = subject;
       this.value = value;
       this.ordinalnumber = ordinalnumber;
       this.isdeleted = isdeleted;
       this.createddate = createddate;
       this.createdby = createdby;
       this.modifieddate = modifieddate;
       this.modifiedby = modifiedby;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Class getClass() {
        return this.class;
    }
    
    public void setClass(Class class) {
        this.class = class;
    }
    public Schoolyear getSchoolyear() {
        return this.schoolyear;
    }
    
    public void setSchoolyear(Schoolyear schoolyear) {
        this.schoolyear = schoolyear;
    }
    public Scoretype getScoretype() {
        return this.scoretype;
    }
    
    public void setScoretype(Scoretype scoretype) {
        this.scoretype = scoretype;
    }
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public Float getValue() {
        return this.value;
    }
    
    public void setValue(Float value) {
        this.value = value;
    }
    public Integer getOrdinalnumber() {
        return this.ordinalnumber;
    }
    
    public void setOrdinalnumber(Integer ordinalnumber) {
        this.ordinalnumber = ordinalnumber;
    }
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
    public String getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }




}


