package pojos;
// Generated Aug 5, 2020 10:41:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

    private Long id;
    private Ethnic ethnic;
    private Nationality nationality;
    private Religion religion;
    private String code;
    private String name;
    private String phone;
    private String identifycard;
    private String email;
    private String avatarpath;
    private String gender;
    private Date birth;
    private String address;
    private String status;
    private Boolean isdeleted;
    private Date createddate;
    private String createdby;
    private Date modifieddate;
    private String modifiedby;
    private Set conducts = new HashSet(0);
    private Set observations = new HashSet(0);
    private Set relativeses = new HashSet(0);
    private Set studentofclasses = new HashSet(0);
    private Set scores = new HashSet(0);

    public Student() {
    }

    public Student(Date createddate, Date modifieddate) {
        this.createddate = createddate;
        this.modifieddate = modifieddate;
    }

    public Student(Ethnic ethnic, Nationality nationality, Religion religion, String code, String name, String phone, String identifycard, String email, String avatarpath, String gender, Date birth, String address, String status, Boolean isdeleted, Date createddate, String createdby, Date modifieddate, String modifiedby, Set conducts, Set observations, Set relativeses, Set studentofclasses, Set scores) {
        this.ethnic = ethnic;
        this.nationality = nationality;
        this.religion = religion;
        this.code = code;
        this.name = name;
        this.phone = phone;
        this.identifycard = identifycard;
        this.email = email;
        this.avatarpath = avatarpath;
        this.gender = gender;
        this.birth = birth;
        this.address = address;
        this.status = status;
        this.isdeleted = isdeleted;
        this.createddate = createddate;
        this.createdby = createdby;
        this.modifieddate = modifieddate;
        this.modifiedby = modifiedby;
        this.conducts = conducts;
        this.observations = observations;
        this.relativeses = relativeses;
        this.studentofclasses = studentofclasses;
        this.scores = scores;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Ethnic getEthnic() {
        return this.ethnic;
    }

    public void setEthnic(Ethnic ethnic) {
        this.ethnic = ethnic;
    }

    public Nationality getNationality() {
        return this.nationality;
    }

    public void setNationality(Nationality nationality) {
        this.nationality = nationality;
    }

    public Religion getReligion() {
        return this.religion;
    }

    public void setReligion(Religion religion) {
        this.religion = religion;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getIdentifycard() {
        return this.identifycard;
    }

    public void setIdentifycard(String identifycard) {
        this.identifycard = identifycard;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAvatarpath() {
        return this.avatarpath;
    }

    public void setAvatarpath(String avatarpath) {
        this.avatarpath = avatarpath;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getBirth() {
        return this.birth;
    }

    public void setBirth(Date birth) {
        this.birth = birth;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Boolean getIsdeleted() {
        return this.isdeleted;
    }

    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    public Date getCreateddate() {
        return this.createddate;
    }

    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public String getCreatedby() {
        return this.createdby;
    }

    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }

    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public String getModifiedby() {
        return this.modifiedby;
    }

    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Set getConducts() {
        return this.conducts;
    }

    public void setConducts(Set conducts) {
        this.conducts = conducts;
    }

    public Set getObservations() {
        return this.observations;
    }

    public void setObservations(Set observations) {
        this.observations = observations;
    }

    public Set getRelativeses() {
        return this.relativeses;
    }

    public void setRelativeses(Set relativeses) {
        this.relativeses = relativeses;
    }

    public Set getStudentofclasses() {
        return this.studentofclasses;
    }

    public void setStudentofclasses(Set studentofclasses) {
        this.studentofclasses = studentofclasses;
    }

    public Set getScores() {
        return this.scores;
    }

    public void setScores(Set scores) {
        this.scores = scores;
    }

}
