package pojos;
// Generated Aug 5, 2020 10:41:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import qlhsc3.Generic;

/**
 * TeacherAssignment generated by hbm2java
 */
public class TeacherAssignment extends Generic implements java.io.Serializable {

    private SchoolClass schoolClass;
    private SchoolYear schoolYear;
    private Semester semester;
    private Subject subject;
    private Teacher teacher;

    public TeacherAssignment() {
    }

    public TeacherAssignment(SchoolClass schoolClass, SchoolYear schoolYear, Semester semester, Subject subject, Teacher teacher, Boolean isDeleted, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
        this.schoolClass = schoolClass;
        this.schoolYear = schoolYear;
        this.semester = semester;
        this.subject = subject;
        this.teacher = teacher;
        this.isDeleted = isDeleted;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.modifiedDate = modifiedDate;
        this.modifiedBy = modifiedBy;
    }

    public SchoolClass getSchoolClass() {
        return this.schoolClass;
    }

    public void setSchoolClass(SchoolClass schoolClass) {
        this.schoolClass = schoolClass;
    }

    public SchoolYear getSchoolYear() {
        return this.schoolYear;
    }

    public void setSchoolYear(SchoolYear schoolYear) {
        this.schoolYear = schoolYear;
    }

    public Semester getSemester() {
        return this.semester;
    }

    public void setSemester(Semester semester) {
        this.semester = semester;
    }

    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public Teacher getTeacher() {
        return this.teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

}
