package pojos;
// Generated Aug 5, 2020 10:41:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import qlhsc3.Officer;

/**
 * Teacher generated by hbm2java
 */
public class Teacher extends Officer implements java.io.Serializable {

    private Subject subject;

    public Teacher() {
    }

    public Teacher(Account account, Subject subject, String code, String name, String phone, String avatarpath, String gender, Date birth, String address, Integer salary, Boolean isDeleted, Date createdDate, String createdBy, Date modifiedDate, String modifiedBy) {
        this.account = account;
        this.subject = subject;
        this.code = code;
        this.name = name;
        this.phone = phone;
        this.avatarpath = avatarpath;
        this.gender = gender;
        this.birth = birth;
        this.address = address;
        this.salary = salary;
        this.isDeleted = isDeleted;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.modifiedDate = modifiedDate;
        this.modifiedBy = modifiedBy;
    }

    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

}
